name: barber_booking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.1
  supabase: ^0.2.15
  ionicons: ^0.1.2
  auto_size_text: ^3.0.0
  flutter_map: ^0.14.0
  geolocator: ^8.2.0
  camera: ^0.9.4+16
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  google_sign_in: ^5.2.4
  extended_image: ^6.0.2+1
  cloud_firestore: ^3.1.10
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: bitter
      fonts:
        - asset: assets/fonts/Bitter-Regular.ttf
          style: normal

