// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD028VKGmLY8eZETlKLhnAvnDjpeFb_D04',
    appId: '1:1066886691623:web:420e209458a122bc5a4702',
    messagingSenderId: '1066886691623',
    projectId: 'barber-shop-27639',
    authDomain: 'barber-shop-27639.firebaseapp.com',
    storageBucket: 'barber-shop-27639.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl4shPxsf_Z42AfW12IsR66tKZENhI0DU',
    appId: '1:1066886691623:android:2bd8bef8190a294c5a4702',
    messagingSenderId: '1066886691623',
    projectId: 'barber-shop-27639',
    storageBucket: 'barber-shop-27639.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhhcaAIlhF899s5vJCWV3EQAH1DB2IvU4',
    appId: '1:1066886691623:ios:e07f78bd6f0fa0ea5a4702',
    messagingSenderId: '1066886691623',
    projectId: 'barber-shop-27639',
    storageBucket: 'barber-shop-27639.appspot.com',
    androidClientId: '1066886691623-lf34n1fmh3hiomril2te4vt4jc26qenh.apps.googleusercontent.com',
    iosClientId: '1066886691623-f9uo4lurpf8vfrfk9k461qhakdpashjb.apps.googleusercontent.com',
    iosBundleId: 'com.mahmoud.barberBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhhcaAIlhF899s5vJCWV3EQAH1DB2IvU4',
    appId: '1:1066886691623:ios:e07f78bd6f0fa0ea5a4702',
    messagingSenderId: '1066886691623',
    projectId: 'barber-shop-27639',
    storageBucket: 'barber-shop-27639.appspot.com',
    androidClientId: '1066886691623-lf34n1fmh3hiomril2te4vt4jc26qenh.apps.googleusercontent.com',
    iosClientId: '1066886691623-f9uo4lurpf8vfrfk9k461qhakdpashjb.apps.googleusercontent.com',
    iosBundleId: 'com.mahmoud.barberBooking',
  );
}
